# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'Affinitee' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Affinitee
  
  pod 'AwesomeTextFieldSwift'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'LGButton'
  pod 'SwiftMessages'
  pod 'PMSuperButton'
  pod 'YPImagePicker'

  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  
  target 'AffiniteeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AffiniteeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
